### ISSUE TITLE
Build fails if your node binary isn't called nodejs

### ISSUE THREAD

**Issue by jonaslund** [easybotics/node-rpi-rgb-led-matrix#1]
Easily fixed by changing this line in binding.gyp
`	        "include_dirs": [ "./external/matrix/include", "./include/", "<!(nodejs -e \"require('nan')\")" ]
`

Should be fixed

**Comment by keptan** [comment]
thanks ill look into this

**Comment by redandinvisible** [comment]
I am having the same problem. Is there a workaround by any chance?

**Comment by redandinvisible** [comment]
In case it helps others:

I cloned this repo and made it a local dependency.  Then I changed the line in the local binding.gyp so the node binary was just called node.  Tried ```npm install``` again which gave a new error ```make: *** No rule to make target `Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/transformer.o', needed by `Release/rpi-rgb-led-matrix.a'.```.

Turns out this was caused by some clever cross-github linking in the ```external``` directory to [this "rpi-rgb-led-matrix" github repo](https://github.com/hzeller/rpi-rgb-led-matrix/tree/8189a56609eb87bcb1188201d07004186af1e17b).  So I cloned the contents of that repo into the external directory.  Removed the uneeded .git directories.  And it now builds.

**Comment by samturner3** [comment]
+1 
![Screen Shot 2019-05-28 at 3 17 38 pm](https://user-images.githubusercontent.com/14887388/58452739-c47c5380-815b-11e9-9fd9-e58555075932.png)

**Comment by keptan** [comment]
@redandinvisible Your issue is just a matter of checking out submodules, I should make that clearer in the readme probably 
when you pull from npm this isn't an issue

**Comment by keptan** [comment]
https://github.com/easybotics/node-rpi-rgb-led-matrix/commit/e4bae0bc62e05c34663e9733c5dba07a27ffaf33

finally dealing with this
